[TPCH]
	DGHost = "localhost"
	DGPort = 5432 
	Db = "tpch1pax"
	Staging = "/home/ftian/oss/data/bench/staging"
	Scale = 1
	DDL = "mktab-fao-pax.sql" 
	Ext = "XDR"
	Gucs = ["set statement_mem = 1000000"] 
