[TPCH]
	DGHost = "localhost"
	DGPort = 5432
	Db = "tpch1f"
	Staging = "/home/ftian/oss/data/bench/staging"
	Scale = 1
	DDL = "mktab-f.sql" 
	Ext = "XDR"
	Orca = 0
	Vitesse = 1
	StatementMem = 1000000
