[TPCH]
	DGHost = "localhost"
	DGPort = 5432 
	Db = "tpch10f"
	Staging = "/home/ftian/oss/data/bench/staging"
	Scale = 10
	DDL = "mktab-f.sql" 
	Ext = "XDR"
	Gucs = ["set vitesse.enable = 1", "set statement_mem = 1000000"] 
