tpch1f:
	createdb tpch1f
	psql -f mktab-f.sql tpch1f
	psql -f mkview-n.sql tpch1f
	psql -f load.sql tpch1f

tpch10fao:
	createdb tpch10fao
	psql -f mktab-fao.sql tpch10fao
	psql -f mkview-n.sql tpch10fao
	psql -f load.sql tpch10fao
